oc_platform_home:
    path:     /
    defaults: { _controller: OCPlatformBundle:Advert:index }

oc_platform_test_template:
    path:     /template
    defaults: { _controller: OCPlatformBundle:Advert:template }

oc_platform_homepage:
    path:     /{page}
    defaults: { _controller: OCPlatformBundle:Advert:index }
    requirements:
        page: \d*
    
helloWord:
    path:     /helloWord
    defaults: { _controller: OCPlatformBundle:Advert:index}

oc_platform_view:
    path:     /advert/{id}
    defaults: { _controller: OCPlatformBundle:Advert:view}
    requirements:
        id: \d+


oc_platform_add:
    path:     /add
    defaults: { _controller: OCPlatformBundle:Advert:add}

oc_platform_edit:
    path: /edit/{id}
    defaults: {_controller: OCPlatformBundle:Advert:edit}
    requirements:
       id: \d+

oc_platform_delete:
    path: /delete/{id}
    defaults: {_controller: OCPlatformBundle:Advert:delete}
    requirements:
       id: \d+
