<?php

namespace BackendBundle\Repository;

/**
 * ClasseTherapeutiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasseTherapeutiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
