<?php

namespace BackendBundle\Repository;

/**
 * ImageArticleRepositoty
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
