<?php

namespace BackendBundle\Repository;

/**
 * ImageArtRepositoty
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageArtRepository extends \Doctrine\ORM\EntityRepository
{
}
